### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by mohitjawanjal** [feat7/Surface#5]
Wanted to contribute to this, but can't see any Contribution guidelines or a gitter channel. If it is active can we hop on there and discuss? Thanks.

**Comment by feat7** [comment]
Sure it is!
Contributions are welcome. Due to my busy schedule, I am not able to contribute to the project.
But few people are willing to contribute. We can get going!

**Comment by mohitjawanjal** [comment]
Great. As I asked is there a gitter channel or can you create one?? Fair
word of warning that I am pretty new to OSS so I will need some guidance :-)

**Comment by feat7** [comment]
You can access: [Gitter](https://gitter.im/SurfaceFramework/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link)
Contribution guidelines are simple.
1. Fork (and keep updated with the original repo)
2. One feature of one branch. Don't mix up things.
3. Create a pull request. Description and title should make good sense.
4. After reviewing branch will be merged.
